import { defineStore } from "pinia";

export const UseEasterEggs = defineStore("UseEasterEggs", {
  state: () => {
    return {
      pigEasterEggs: [
        "El primer sistema de refrigeración por compresión: Fue desarrollado en 1834 por Jacob Perkins y es el precursor de los refrigeradores modernos.",
        "El popcorn tiene una historia antigua: Los indígenas americanos ya hacían palomitas de maíz hace más de 5,000 años.",
        "La tortilla de maíz es un alimento básico en Mesoamérica: Ha sido un alimento fundamental para las culturas indígenas de México y Centroamérica durante milenios.",
        "La primera pizza en Estados Unidos: Fue servida en Nueva York en 1905 por un inmigrante italiano llamado Gennaro Lombardi.",
        "La leche de almendra tiene orígenes antiguos: Los musulmanes medievales en la región del Medio Oriente la usaban como alternativa a la leche animal.",
        "Las fresas son más efectivas en su forma natural: Las fresas frescas tienen más antioxidantes que las procesadas en productos.",
        "El wok se originó en China: Es un utensilio de cocina versátil que ha sido usado en la cocina china durante más de 2,000 años.",
        "El queso azul: Tiene moho en su interior, lo que le da su sabor característico y se desarrolla durante un proceso de envejecimiento.",
        "Esta app usa Vue Router para que cada ruta se cargue de manera fluida y sin recargar.",
        "Esta app tiene su estado global manejado por Pinia, manteniendo todo perfectamente organizado.",
        "Esta app es una SPA, lo que significa que nunca tendrás que esperar recargas lentas.",
        "Esta app está diseñada con Tailwind CSS para asegurar que cada pixel esté en su lugar.",
        "Esta app utiliza Pinia para manejar los datos de forma eficiente y reactiva.",
        "Esta app sigue funcionando incluso sin conexión gracias a su tecnología PWA.",
        "Esta app navega entre páginas sin recargas gracias a Vue Router.",
        "Esta app está hecha con Vue 3, Pinia y Tailwind, una combinación moderna y poderosa.",
        "Esta app usa Pinia para gestionar su estado de forma fluida y eficiente.",
        "Esta app utiliza Tailwind y Vue 3, una pareja perfecta para crear interfaces rápidas y modernas.",
        "La primera máquina para hacer hielo: Fue inventada por el químico estadounidense John Gorrie en 1844.",
        "El origen del dulce de leche: Aunque es popular en América Latina, tiene orígenes disputados, con versiones en Francia y España.",
        "El sushi significa 'arroz ácido': El término se refiere a la fermentación del arroz usado en la preparación de sushi tradicional.",
        "La comida de calle tiene una larga historia: En la antigua Roma y Grecia, los vendedores ambulantes ofrecían comida rápida similar a la comida de calle actual.",
        "El pan de masa madre: Se ha utilizado durante siglos y es conocido por su sabor ácido y su textura crujiente.",
        "Las aceitunas pueden ser verdes o negras: La diferencia de color depende del grado de maduración y del proceso de curado.",
        "El primer uso de la batidora eléctrica: Se remonta a 1922 y fue inventada por la empresa Hamilton Beach.",
        "La comida vegana tiene siglos de historia: Aunque popular hoy en día, las dietas basadas en plantas han existido en varias culturas a lo largo de la historia.",
        "La primera máquina de café espresso automática: Fue desarrollada en 1961 y revolucionó el consumo de café en todo el mundo.",
        "El coco tiene múltiples usos: Desde alimentos y bebidas hasta productos cosméticos y materiales de construcción.",
        "La primera receta de chocolate caliente: Data de los antiguos mayas y aztecas, quienes bebían una mezcla de cacao, agua y especias.",
        "Esta app es una verdadera PWA, ¡puedes usarla sin conexión y agregarla a tu pantalla de inicio!",
        "Esta app usa Tailwind CSS para aplicar estilos precisos sin escribir líneas extra de código.",
        "Esta app utiliza Vue Router para mantener la navegación rápida y eficiente.",
        "Esta app está controlada por Pinia, lo que asegura que todos los datos estén siempre sincronizados.",
        "Esta app carga todo dinámicamente, ¡gracias a su arquitectura de SPA!",
        "Esta app está construida para ser rápida y moderna, gracias a Vue 3 y Tailwind CSS.",
        "La tradición del té en la tarde: Se originó en Inglaterra en el siglo XIX como una forma de combatir el hambre entre el almuerzo y la cena.",
        "Las patatas fritas fueron inventadas en Bélgica: Aunque las papas fritas se asocian con Francia, en realidad se originaron en Bélgica.",
        "La primera batidora de mano eléctrica: Fue patentada en 1950 por la empresa Sunbeam.",
        "La miel se utiliza como conservante natural: Debido a su alta acidez y baja humedad, puede prevenir el crecimiento de bacterias.",
        "El primer refrigerador de cocina: Se introdujo en el mercado a finales del siglo XIX y cambió la forma en que se almacenaban los alimentos.",
        "El pasto de cebada es el ingrediente principal en el whisky: Se utiliza para fermentar y destilar la bebida alcohólica.",
        "Esta app está sincronizada gracias a Pinia, manejando el estado global sin problemas.",
        "Esta app es una SPA, optimizando la velocidad y fluidez de cada interacción.",
        "Esta app tiene su diseño controlado por Tailwind CSS, para garantizar consistencia y velocidad.",
        "El primer aparato de cocina de microondas comercial: Fue desarrollado en 1947 y fue conocido como el 'Radarange'.",
        "La pasta con salsa de tomate: Aunque ahora es común en Italia, fue un invento más reciente, popularizado en el siglo XVI.",
        "El ajo tiene propiedades antibacterianas: Ha sido utilizado en la medicina tradicional para tratar diversas infecciones y enfermedades.",
        "La primera receta de mayonesa: Data de 1756 en Francia y se convirtió en un aderezo popular en todo el mundo.",
        "Las primeras conservas enlatadas: Fueron inventadas en Francia a principios del siglo XIX para conservar alimentos durante largos periodos.",
        "El queso parmesano tiene una historia larga: Se ha producido en Italia desde al menos el siglo XII y es conocido por su sabor fuerte y salado.",
        "Las nueces tienen altos niveles de antioxidantes: Pueden ayudar a reducir la inflamación y mejorar la salud del corazón.",
        "La primera receta de helado de chocolate: Se creó en Italia en el siglo XVIII y se convirtió en un dulce popular en todo el mundo.",
        "Las primeras máquinas de hacer hielo: Se desarrollaron en el siglo XIX y ayudaron a la conservación y refrigeración de alimentos.",
        "La cocina francesa es conocida por su técnica: Incluye técnicas clásicas como la reducción, el flambé y la cocción a fuego lento.",
        "El primer libro de recetas conocido: Se remonta a la antigua Roma y se llama 'De Re Coquinaria'.",
        "El origen de la crema batida: Se remonta a la Francia del siglo XVII y se convirtió en un popular acompañamiento para postres.",
        "El primer electrodoméstico de cocina: Fue el horno eléctrico, patentado en 1896 por Albert H. Butz.",
        "El origen del curry en polvo: Es una mezcla de especias que se desarrolló en el siglo XIX en la India y fue popularizada por los colonos británicos.",
        "La primera receta de gelatina: Se originó en el siglo XV y era conocida por sus propiedades gelificantes naturales.",
        "La cultura del café en Italia: Se ha convertido en un arte, con especialidades como el espresso, el cappuccino y el macchiato.",
        "La primera receta de panecillos: Se remonta a la antigua Grecia y Roma, donde se usaban técnicas similares a las actuales para hacer pan.",
        "El origen de la ensalada César: Se creó en México en la década de 1920 por César Cardini, un chef italiano.",
        "El queso feta es originario de Grecia: Es un queso salado y desmenuzable que ha sido un alimento básico en la dieta griega durante siglos.",
        "La primera pizza de pepperoni: Fue creada en los Estados Unidos en la década de 1950 y se ha convertido en una de las pizzas más populares.",
        "El origen de las galletas: Se remontan a la antigua Persia, donde se horneaban dulces similares a las galletas modernas.",
        "Las especias tienen una larga historia: Han sido utilizadas en la cocina y la medicina desde la antigüedad en culturas de todo el mundo.",
        "El vino tiene una larga tradición: Se ha producido desde la antigüedad en regiones como Mesopotamia y Egipto.",
        "La primera máquina de café en cápsulas: Fue desarrollada por la empresa Nespresso en 1986 y revolucionó el consumo de café en casa.",
        "El origen del hummus: Es un alimento tradicional del Medio Oriente y ha sido consumido en la región durante siglos.",
        "La primera receta de muffins: Data de la Inglaterra del siglo XVIII y se hizo popular en los Estados Unidos en el siglo XIX.",
        "Las primeras recetas de postres: Se remonta a la antigua Roma y Grecia, donde se preparaban dulces con miel y frutas.",
        "El primer microondas comercial: Fue inventado en 1947 y era un aparato grande y costoso que revolucionó la cocina.",
        "El origen de los tacos: Se remonta a las antiguas civilizaciones mesoamericanas, donde se utilizaban tortillas para envolver alimentos.",
        "La primera máquina para hacer pasta: Fue patentada en 1870 en Italia y ayudó a popularizar la pasta en todo el mundo.",
        "Las primeras recetas de galletas saladas: Se originaron en la antigua Roma y eran conocidas como 'biscotti'.",
        "El origen del sushi: Es una técnica de conservación de pescado que se desarrolló en el sudeste asiático y luego se popularizó en Japón.",
        "El primer dispositivo de cocina para medir temperatura: Fue el termómetro de cocina, inventado en el siglo XIX para asegurar la cocción adecuada.",
        "El primer refrigerador doméstico: Se introdujo en el mercado en la década de 1920 y revolucionó la forma en que se almacenaban los alimentos.",
        "La primera receta de pasta con queso: Se remonta al siglo XIV en Italia y se convirtió en un plato popular durante la Edad Media.",
        "El primer electrodoméstico para hacer pan: Fue el panadero automático, inventado en 1986 en Japón.",
        "El origen de la mermelada: Se remonta a la antigüedad y era una forma de conservar frutas con azúcar.",
        "La primera máquina para hacer helado: Fue desarrollada en el siglo XIX y ayudó a popularizar el helado en todo el mundo.",
        "Las primeras recetas de pan de plátano: Se originaron en los Estados Unidos en la década de 1930 y se hicieron populares durante la Gran Depresión.",
        "El origen del queso ricotta: Es un queso italiano que se hace a partir del suero de leche y ha sido producido en Italia durante siglos.",
        "La primera máquina para hacer café de filtro: Fue patentada en 1954 y revolucionó la forma en que se prepara el café en casa.",
        "El origen de la pasta rellena: Se remonta a la antigua Roma y Grecia, donde se rellenaban pastas con ingredientes como carne y queso.",
        "El primer electrodoméstico para hacer yogurt: Fue inventado en la década de 1950 y ayudó a popularizar el yogurt en los hogares.",
        "Las primeras recetas de pan integral: Se remontan a la antigua Egipto y se hacían con granos enteros molidos.",
        "El origen del queso cheddar: Es un queso inglés que se ha producido desde el siglo XII en la aldea de Cheddar en Somerset.",
        "La primera máquina para hacer pan de molde: Fue patentada en 1928 y ayudó a popularizar el pan de molde en los hogares.",
        "El primer dispositivo de cocina para cocinar al vacío: Fue desarrollado en la década de 1970 por el chef francés Georges Pralus.",
        "El origen de la pasta al pesto: Es una receta tradicional italiana que utiliza albahaca, piñones, ajo y queso parmesano.",
        "La primera máquina para hacer café espresso manual: Fue desarrollada en Italia en la década de 1940 y revolucionó la forma de preparar café.",
        "El primer libro de recetas en inglés: Se publicó en 1796 y se titulaba 'American Cookery' por Amelia Simmons.",
        "El origen del queso gouda: Es un queso holandés que se ha producido en la ciudad de Gouda desde el siglo XII.",
        "La primera máquina para hacer pan de ajo: Fue patentada en 1985 y revolucionó la forma en que se preparaba este pan en los hogares.",
        "El primer dispositivo de cocina para cocción lenta: Fue el 'slow cooker', inventado en la década de 1970 en Estados Unidos.",
        "El origen del sushi con pescado crudo: Se popularizó en Japón durante el siglo XIX y se convirtió en una parte importante de la cocina japonesa.",
        "La primera máquina para hacer helado de yogurt: Fue desarrollada en la década de 1980 y ayudó a popularizar el yogurt helado.",
        "El primer libro de recetas de cocina francesa: Fue publicado en 1651 por el chef François Pierre La Varenne y se considera uno de los primeros libros de cocina moderna.",
        "El origen del queso mozzarella: Es un queso italiano que se produce con leche de búfala y se ha hecho en la región de Campania desde hace siglos.",
        "La primera máquina para hacer pan sin gluten: Fue inventada en 2000 y ayudó a atender la demanda de pan sin gluten.",
        "Esta app aplica Tailwind CSS, que ofrece clases de utilidad que hacen el desarrollo más rápido y consistente.",
        "Esta app funciona con Pinia, manteniendo el estado sincronizado y reactivo en todo momento.",
        "Esta app es una PWA, puedes agregarla a tu pantalla de inicio y usarla como si fuera una app nativa.",
        "Esta app aprovecha Vue 3 y su Composition API para escribir código más limpio y eficiente.",
        "Esta app está diseñada con Tailwind, permitiendo un desarrollo visual rápido con clases útiles.",
        "El primer dispositivo de cocina para preparar sushi: Fue desarrollado en Japón en la década de 1970 y facilitó la preparación de sushi en casa.",
        "El origen de la tarta de manzana: Se remonta a la antigua Roma y ha sido una popular tarta en muchas culturas desde entonces.",
        "La primera máquina para hacer pasta fresca: Fue patentada en 1961 en Italia y ayudó a popularizar la pasta fresca en los hogares.",
        "El origen del queso gruyère: Es un queso suizo que se ha producido en la región de Gruyères desde el siglo XII.",
        "El primer dispositivo de cocina para cocinar a la parrilla: Fue el grill eléctrico, inventado en 1952 y popularizado en las cocinas domésticas.",
        "El origen de la cocina Tex-Mex: Es una mezcla de la cocina tradicional mexicana y los ingredientes y estilos de cocina del suroeste de Estados Unidos.",
        "La primera máquina para hacer pan de pita: Fue inventada en la década de 1960 y ayudó a popularizar el pan de pita en los hogares.",
        "El primer libro de recetas de cocina italiana: Fue publicado en el siglo XV y se titulaba 'Libro de Arte Coquinaria' por el chef Maestro Martino.",
        "El origen del queso camembert: Es un queso francés que se ha producido en la región de Normandía desde el siglo XVIII.",
        "Esta app usa Vue Router para cambiar entre páginas sin interrupciones.",
        "Esta app se mantiene en perfecto funcionamiento gracias a Pinia, que maneja el estado global.",
        "Esta app está hecha para ofrecer una experiencia rápida y fluida como SPA.",
        "Esta app tiene todo lo necesario para ser rápida y eficiente, gracias a Vue 3 y Tailwind CSS.",
        "Esta app está diseñada como una PWA, permitiéndote usarla incluso cuando no tienes acceso a internet.",
        "Esta app utiliza el poder de la Composition API para organizar cada parte de su funcionalidad.",
        "Esta app navega entre secciones sin interrupciones, gracias a Vue Router.",
        "Esta app se mantiene organizada gracias a Pinia, que controla todo su estado.",
        "Esta app aplica Tailwind CSS para lograr un diseño moderno y flexible sin mucho esfuerzo.",
        "Esta app está construida como una SPA, lo que significa una experiencia más rápida y fluida.",
        "La primera máquina para hacer helado suave: Fue desarrollada en la década de 1950 y ayudó a popularizar el helado suave en los Estados Unidos.",
        "El origen de la ensalada caprese: Es una ensalada italiana que se ha hecho en la región de Campania desde el siglo XX.",
        "La primera máquina para hacer batidos: Fue patentada en 1922 y ayudó a popularizar los batidos en los hogares.",
        "El origen del queso ricotta: Es un queso italiano que se ha producido desde la antigüedad y se hace con el suero de leche.",
        "La primera máquina para hacer galletas: Fue inventada en 1951 y ayudó a popularizar la producción de galletas en los hogares.",
        "El primer libro de recetas de cocina japonesa: Fue publicado en el siglo XVIII y se titula 'Ryori Monogatari'.",
        "El origen del queso provolone: Es un queso italiano que se ha producido en la región de Campania desde el siglo XIX.",
        "Esta app está hecha con Vue 3, Pinia y Tailwind, una combinación ganadora.",
        "Esta app es una PWA, lo que significa que puedes seguir usándola incluso cuando no tienes conexión.",
        "Esta app organiza su estructura con la Composition API, lo que hace que el código sea fácil de mantener.",
        "Esta app navega entre páginas sin recargar gracias a Vue Router.",
        "Esta app está impulsada por Pinia, manteniendo todo en perfecto orden.",
        "Esta app es rápida y eficiente gracias a su diseño como SPA.",
        "La primera máquina para hacer pan de centeno: Fue inventada en la década de 1980 y ayudó a popularizar el pan de centeno en los hogares.",
        "El origen de la pasta: Aunque a menudo se asocia con Italia, la pasta ya se consumía en China mucho antes de que se popularizara en Europa.",
        "El aguacate es una fruta: A pesar de su sabor salado, el aguacate es una fruta, no una verdura. Más específicamente, es una baya.",
        "El primer libro de cocina: El primer libro de cocina conocido se atribuye a la antigua Roma y se titula 'Apicius'.",
        "La sal como conservante: Antes de la invención de los refrigeradores, la sal era uno de los principales métodos para conservar alimentos.",
        "El chocolate y el cacao: Los mayas y aztecas utilizaban el cacao no solo como alimento, sino también como moneda.",
        "El huevo perfecto: La forma tradicional de cocinar un huevo 'perfecto' se logra a los 6-7 minutos de cocción en agua hirviendo.",
        "La importancia del aceite de oliva: El aceite de oliva se ha utilizado en la cocina desde hace más de 5,000 años y es esencial en la dieta mediterránea.",
        "El origen de la pizza: Aunque la pizza moderna es italiana, los antiguos griegos y romanos ya comían pan plano con hierbas y aceites.",
        "El azúcar en la cocina: El azúcar no solo endulza, sino que también juega un papel crucial en la textura y conservación de productos horneados.",
        "La ciencia detrás del pan: La fermentación de la levadura convierte los azúcares en gas, creando burbujas en la masa del pan.",
        "La primera receta registrada de pan: Se encontró en la antigua Mesopotamia y databa de hace más de 6,000 años.",
        "Las zanahorias eran originalmente moradas: Las zanahorias naranjas que conocemos hoy se desarrollaron en los Países Bajos en el siglo XVII.",
        "El origen del sushi: El sushi comenzó como una técnica de conservación de pescado en el sudeste asiático, fermentado con arroz.",
        "Esta app responde de manera ágil, gracias a su naturaleza de SPA.",
        "Esta app está organizada con Composition API, lo que facilita el mantenimiento y escalabilidad.",

        "Esta app es una PWA, lo que significa que puedes usarla incluso cuando no tienes conexión.",
        "El café fue descubierto por los etíopes: Según la leyenda, un pastor de cabras etíope notó que sus cabras estaban muy energéticas después de comer bayas de café.",
        "El aceite de coco tiene múltiples usos: Además de en la cocina, se utiliza en productos de belleza y como agente de limpieza.",
        "El origen del helado: Los antiguos persas ya disfrutaban de una mezcla de nieve y jarabe de frutas, similar al helado moderno.",
        "La primera receta de pasta con salsa: La combinación de pasta con salsa de tomate se popularizó en Italia en el siglo XVI.",
        "Los tomates eran considerados venenosos en Europa: En el siglo XVIII, los tomates eran conocidos como 'manzanas venenosas' en Europa.",
        "La quinoa no es un cereal: Aunque se usa como tal, la quinoa es en realidad una semilla de una planta relacionada con las espinacas.",
        "El ajo y sus beneficios: El ajo ha sido utilizado durante milenios por sus propiedades medicinales, además de su uso culinario.",
        "Las uvas sin semillas fueron desarrolladas en 2001: Antes de eso, todas las uvas disponibles tenían semillas.",
        "Esta app utiliza Vue 3 y Tailwind CSS para crear interfaces eficientes y atractivas.",
        "Esta app sigue funcionando incluso sin conexión gracias a la tecnología PWA.",
        "Esta app aprovecha la Composition API para mantener el código limpio y escalable.",
        "Esta app cambia de página rápidamente gracias a Vue Router, sin recargas innecesarias.",
        "La primera olla de presión: Se inventó en 1679 por el físico francés Denis Papin, aunque se popularizó en el siglo XX.",
        "La miel es un conservante natural: Gracias a su bajo contenido de agua y alto nivel de acidez, la miel puede durar indefinidamente.",
        "Las primeras conservas enlatadas: Fueron inventadas en Francia en 1809 como una forma de conservar alimentos para los ejércitos.",
        "La comida rápida tiene una larga historia: Aunque moderna en su forma, el concepto de comida rápida existe desde la antigüedad, con vendedores ambulantes en Roma y Grecia.",
        "La zanahoria originalmente era más amarga: Las variedades modernas han sido cultivadas para ser más dulces.",
        "El aguacate contiene más potasio que los plátanos: Es una excelente fuente de potasio y grasas saludables.",
        "Esta app está gestionada por Pinia, asegurando que el estado global esté siempre sincronizado.",
        "Esta app es una SPA, lo que significa que carga de forma dinámica y rápida.",
        "Esta app está hecha con Vue 3 y Tailwind, para un desarrollo moderno y eficiente.",
        "Esta app puede ser usada sin conexión, gracias a que es una PWA.",
        "Esta app organiza su código de manera eficiente con la Composition API de Vue 3.",
        "Esta app navega sin interrupciones gracias a Vue Router.",
        "Esta app mantiene su estado en perfecto orden con Pinia.",
        "Esta app está diseñada para ser rápida y fluida, ¡gracias a su arquitectura como SPA!",
        "Esta app está estilizada con Tailwind CSS, ¡cada diseño es preciso y rápido!",
        "Esta app aprovecha Vue 3, Pinia y Tailwind para ofrecer la mejor experiencia de usuario.",
        "Esta app sigue funcionando incluso sin conexión, gracias a su tecnología PWA.",
        "Esta app organiza su estructura con la Composition API, facilitando el desarrollo.",
        "Esta app permite navegar sin interrupciones gracias a Vue Router.",
        "Esta app tiene su estado sincronizado gracias a Pinia, manteniendo todo en perfecto orden.",
        "Esta app está diseñada como una SPA, ofreciendo una experiencia rápida y sin recargas.",
        "La cocina francesa y sus técnicas: La cocina francesa ha influido en la gastronomía mundial y es famosa por sus técnicas culinarias refinadas.",
        "El primer microondas: Fue inventado en 1945 por Percy Spencer cuando descubrió que las ondas electromagnéticas podían calentar alimentos.",
        "Las fresas no son berries: Botánicamente, las fresas son un tipo de 'fruto agregado', mientras que las verdaderas bayas son más como las uvas.",
        "El aceite de sésamo es utilizado en muchas culturas: Es común en la cocina asiática y tiene un sabor distintivo y beneficios para la salud.",
        "Las primeras ollas de barro: Se utilizaron en la antigua China para cocinar alimentos y conservarlos.",
        "La primera receta de pizza con piña: Fue creada en Canadá en 1962 por un pizzero griego llamado Sam Panopoulos.",
        "La cocina molecular explora la ciencia: Utiliza técnicas científicas para entender y alterar la forma en que se cocinan los alimentos.",
        "Las naranjas eran originalmente verdes: El color naranja en las naranjas se desarrolla en climas más fríos y más soleados.",
        "El primer frigorífico eléctrico: Se patentó en 1914, revolucionando la conservación de alimentos.",
        "Esta app aprovecha Vue 3 y Tailwind para crear interfaces modernas y rápidas.",
        "Esta app sigue funcionando sin problemas incluso sin internet, gracias a la tecnología PWA.",
        "Esta app mantiene todo organizado y reutilizable con la Composition API.",
        "Esta app cambia de sección sin esfuerzo gracias a Vue Router.",
        "El origami de comida es una tendencia: Crear figuras de origami con comida es una forma artística de presentar platos.",
        "El vinagre tiene propiedades de limpieza: Puede usarse para limpiar superficies debido a su acidez.",
        "Los macarrones tienen una larga historia: Aunque hoy son conocidos como dulces franceses, en realidad se originaron en Italia.",
        "El arroz es un alimento básico mundial: Es la principal fuente de calorías para más de la mitad de la población mundial.",
        "El primer aparato de cocina eléctrica: Fue el hervidor de agua eléctrico, inventado en 1891.",
        "Los pepinos son en realidad frutas: Aunque se tratan como verduras en la cocina, los pepinos son frutos desde el punto de vista botánico.",
        "La carne de cangrejo es muy nutritiva: Es baja en grasa y alta en proteínas y minerales.",
        "Esta app está alimentada por Pinia, que mantiene el estado de la aplicación siempre sincronizado.",
        "Esta app es una SPA, lo que significa que nunca tendrás que esperar largos tiempos de carga.",
        "Esta app está diseñada con Vue 3 y Tailwind para maximizar la eficiencia del desarrollo.",
        "Esta app es una PWA, ¡puedes usarla sin conexión y agregarla a tu pantalla de inicio!",
        "Esta app organiza su código con la Composition API para mantener todo modular y limpio.",
        "Esta app utiliza Vue Router para que puedas navegar sin interrupciones entre sus secciones.",
        "La pasta tiene diferentes formas: Más de 350 formas diferentes de pasta se conocen y cada una tiene una textura y uso culinario únicos.",
        "El chocolate blanco no es realmente chocolate: No contiene sólidos de cacao, solo manteca de cacao, azúcar y leche.",
        "El curry es una mezcla de especias: No es una especia única, sino una combinación de varias especias como cúrcuma, comino y coriandro.",
        "El kiwi es originario de China: Fue conocido como 'grosella china' antes de ser cultivado en Nueva Zelanda y cambiar su nombre.",
        "La primera hamburguesa: Aunque su origen exacto es discutido, se cree que las primeras hamburguesas se sirvieron en Estados Unidos a fines del siglo XIX.",
        "Las alcachofas son flores comestibles: La parte que comemos es el capullo floral no abierto de la planta de alcachofa.",
        "El maíz es originario de América: Fue cultivado por los pueblos indígenas de América mucho antes de la llegada de los europeos.",
        "El primer café espresso: Se desarrolló en Italia a principios del siglo XX y se convirtió en una forma popular de preparar café.",
        "Esta app está hecha con Vue 3, usando el Composition API para una arquitectura moderna y flexible.",
        "Esta app está construida con Tailwind CSS, lo que hace que el diseño sea rápido y preciso sin escribir CSS personalizado.",
        "Esta app utiliza Pinia, una tienda de estado ligera y reactiva que mantiene todo en orden.",
        "Esta app es una SPA, lo que significa que todo se carga dinámicamente sin recargar la página.",
        "Esta app usa Vue Router para hacer que la navegación sea rápida y sin interrupciones.",
        "Esta app está hecha con la magia del Composition API, lo que permite un código más modular y reutilizable.",
        "Las espinacas contienen más hierro que la carne: Aunque el hierro en las espinacas es menos absorbible que el de la carne, sigue siendo una buena fuente.",
        "Las hierbas frescas tienen más sabor: En general, las hierbas frescas tienen un sabor más intenso que sus versiones secas.",
        "Esta app tiene una arquitectura organizada gracias a la Composition API de Vue 3.",
        "Esta app gestiona el estado de forma eficiente con Pinia, para una experiencia fluida.",
        "Esta app está construida con Vue Router, para que navegar entre sus páginas sea rápido y sencillo.",
        "Esta app tiene todo su diseño estilizado con Tailwind CSS, para lograr una interfaz impecable.",
        "Esta app está impulsada por Pinia y Vue 3, manejando su estado de manera impecable.",
        "Esta app es una PWA, así que puedes disfrutarla sin conexión y añadirla a tu pantalla de inicio.",
        "Esta app utiliza la Composition API, organizando su código de manera eficiente y modular.",
        "La pasta al dente es más saludable: Cocinar la pasta al dente hace que tenga un índice glucémico más bajo que la pasta completamente cocida.",
        "El primer yogur comercial: Se vendió por primera vez en el siglo XX y se convirtió en un producto lácteo popular en todo el mundo.",
      ],
    };
  },
  getters: {
    getPigEasterEggs(): string[] {
      return this.pigEasterEggs;
    },
  },
});
// Esta app es realmente una PWA, ¡puedes usarla sin conexión! Además, se actualiza automáticamente en segundo plano.",
