import { defineStore } from "pinia";

export const UseEasterEggs = defineStore("UseEasterEggs", {
  state: () => {
    return {
      pigEasterEggs: [
        "El maíz es uno de los cultivos más antiguos.",
        "La manzana más grande pesó 1.849 kg.",
        "El brócoli es una flor comestible.",
        "El queso fue inventado hace más de 7,000 años.",
        "El durazno y la nectarina son la misma especie.",
        "El helado más antiguo data de hace 4,000 años en China.",
        "La zanahoria más larga tenía 6.2 metros.",
        "El azúcar es el ingrediente más adictivo.",
        "La granada tiene más antioxidantes que el vino tinto.",
        "Los tomates tienen más genes que los humanos.",
        "El atún puede nadar a más de 70 km/h.",
        "La palabra 'whiskey' viene del gaélico que significa 'agua de vida'.",
        "Las papas fritas se inventaron en Bélgica.",
        "El champán solo puede venir de la región de Champagne en Francia.",
        "El caviar es huevas de pescado saladas.",
        "Los cacahuetes crecen bajo tierra.",
        "El calamar más grande jamás capturado pesó más de 450 kg.",
        "El arroz salvaje no es un verdadero arroz.",
        "La sandía es el símbolo de la fertilidad en Egipto.",
        "El té verde se consume desde hace 4,000 años.",
        "El aguacate se considera una baya.",
        "El limón puede limpiar metales.",
        "La leche fue uno de los primeros alimentos procesados por los humanos.",
        "El chocolate blanco no contiene cacao sólido.",
        "El pollo es el tipo de carne más consumida en el mundo.",
        "El azúcar mascabado tiene más nutrientes que el azúcar blanco.",
        "El atún puede vivir más de 20 años.",
        "El corazón humano late aproximadamente 100,000 veces al día.",
        "La piel es el órgano más grande del cuerpo humano.",
        "El cuerpo humano está compuesto en un 60% de agua.",
        "El cerebro humano tiene alrededor de 86 mil millones de neuronas.",
        "Las uñas crecen aproximadamente 3 mm al mes.",
        "Los huesos humanos son más fuertes que el acero del mismo peso.",
        "El ojo humano puede distinguir aproximadamente 10 millones de colores.",
        "La lengua humana tiene alrededor de 8,000 papilas gustativas.",
        "El hígado es el único órgano que puede regenerarse por completo.",
        "Los músculos más pequeños del cuerpo están en el oído medio.",
        "El cuerpo humano tiene 206 huesos en la adultez, pero 270 en la infancia.",
        "El esqueleto humano está compuesto por 206 huesos adultos, pero al nacer tiene 270.",
        "El estómago produce una nueva capa de mucus cada dos semanas para evitar que se digiera a sí mismo.",
        "El músculo más fuerte en relación con su tamaño es el masetero, el músculo que usamos para masticar.",
        "Cada célula en el cuerpo humano tiene un ciclo de vida diferente; algunas viven solo unos días, mientras que otras pueden durar toda la vida.",
        "Los huesos del oído medio (martillo, yunque y estribo) son los más pequeños del cuerpo.",
        "Los huesos son vivos y están en constante cambio; el proceso de remodelación ósea reemplaza el hueso viejo con hueso nuevo.",
        "El cuerpo humano produce aproximadamente 1 a 1.5 litros de saliva al día.",
        "El pulmón derecho es ligeramente más grande que el pulmón izquierdo.",
        "El cuerpo humano tiene aproximadamente 5 a 6 litros de sangre en promedio.",
        "Las células de la piel se renuevan cada 28 días.",
        "La piel tiene tres capas: epidermis, dermis y tejido subcutáneo.",
        "La sensación de cosquilleo es procesada en la parte del cerebro llamada corteza somatosensorial.",
        "El hígado filtra aproximadamente 1.4 litros de sangre por minuto.",
        "Los humanos tienen más de 600 músculos en el cuerpo.",
        "Las mujeres tienen más glándulas sudoríparas que los hombres.",
        "El cuerpo humano puede sobrevivir sin comida durante semanas, pero solo unos días sin agua.",
        "El oído humano puede detectar frecuencias desde 20 Hz hasta 20,000 Hz.",
        "Las huellas dactilares son únicas para cada individuo, incluso para los gemelos idénticos.",
        "El sistema nervioso central está compuesto por el cerebro y la médula espinal.",
        "El cuerpo humano puede generar su propio calor a través de la termogénesis.",
        "Las pestañas tienen una vida útil de aproximadamente 150 a 200 días.",
        "El cerebro representa aproximadamente el 2% del peso total del cuerpo pero utiliza el 20% de la energía del cuerpo.",
        "El músculo cardíaco es el único músculo que no se fatiga.",
        "Cada persona tiene una huella de lengua única.",
        "Los músculos del ojo son los más activos del cuerpo humano.",
        "El tejido adiposo (grasa) puede almacenar más energía que otros tipos de tejidos.",
        "La piel de los dedos tiene una capacidad única para detectar texturas finas.",
        "El intestino delgado tiene una longitud de aproximadamente 6 metros.",
        "El intestino grueso tiene una longitud de aproximadamente 1.5 metros.",
        "Los glóbulos rojos tienen una vida útil de aproximadamente 120 días.",
        "El hueso del fémur es el hueso más largo y fuerte del cuerpo.",
        "El ojo humano tiene tres tipos de conos que permiten distinguir colores: rojo, verde y azul.",
        "Las articulaciones de las manos son extremadamente flexibles y permiten una amplia gama de movimientos.",
        "El sistema inmunológico es responsable de proteger el cuerpo de infecciones y enfermedades.",
        "El páncreas produce insulina, que regula los niveles de azúcar en la sangre.",
        "Los músculos de los brazos y las piernas permiten una gran variedad de movimientos.",
        "El cuerpo humano tiene más de 2 millones de glándulas sudoríparas.",
        "Las células óseas llamadas osteoblastos son responsables de la formación de hueso nuevo.",
        "Los riñones filtran la sangre para eliminar desechos y producir orina.",
        "El hígado también está involucrado en la producción de proteínas importantes para la coagulación de la sangre.",
        "El cuerpo humano tiene un sistema de referencia propio para mantener el equilibrio.",
        "Las lágrimas tienen una función protectora y lubricante para los ojos.",
        "El cuerpo humano tiene un sistema de retroalimentación que regula la temperatura corporal.",
        "El sistema esquelético proporciona estructura y soporte al cuerpo.",
        "Las células de la piel son constantemente reemplazadas por nuevas células.",
        "El cerebro humano es aproximadamente un 75% de agua.",
        "El cuerpo humano tiene un mecanismo de curación natural para reparar heridas y lesiones.",
        "Los músculos del cuello permiten una amplia gama de movimientos de la cabeza.",
        "Las costillas protegen los órganos vitales en el pecho.",
        "El cuerpo humano puede regular la presión arterial para adaptarse a diferentes niveles de actividad.",
        "La piel tiene una función importante en la regulación de la temperatura corporal.",
        "El cuerpo humano tiene un sistema de glándulas que produce hormonas para regular funciones corporales.",
        "El sistema linfático ayuda a eliminar desechos y combatir infecciones.",
        "El sistema circulatorio transporta sangre, nutrientes y oxígeno a través del cuerpo.",
        "El cuerpo humano puede detectar cambios en la presión y la temperatura a través de receptores en la piel.",
        "El tejido conectivo incluye tendones, ligamentos y cartílago, que proporcionan soporte y flexibilidad.",
        "El sistema endocrino regula el crecimiento, el metabolismo y otras funciones a través de hormonas.",
        "Los músculos de la mandíbula son responsables de la masticación y la producción de sonidos.",
        "El cuerpo humano tiene una capacidad notable para adaptarse y aprender nuevas habilidades.",
        "El sistema respiratorio permite la entrada de oxígeno y la eliminación de dióxido de carbono.",
        "El cuerpo humano tiene mecanismos para mantener el equilibrio y la coordinación.",
        "Los receptores en la piel permiten la percepción del tacto, la presión y la temperatura.",
        "El cuerpo humano produce células sanguíneas en la médula ósea.",
        "Las articulaciones permiten el movimiento y la flexibilidad del cuerpo.",
        "El sistema digestivo descompone los alimentos para extraer nutrientes y energía.",
        "El cuerpo humano tiene un sistema de defensa natural contra patógenos y toxinas.",
        "El cerebro controla las funciones corporales y procesa la información sensorial.",
        "El cuerpo humano tiene una capacidad asombrosa para regenerarse y sanar.",
        "El sistema reproductivo permite la reproducción y el desarrollo de nuevas vidas.",
        "Las glándulas sebáceas producen aceite para mantener la piel y el cabello lubricados.",
        "El cuerpo humano tiene una capacidad de memoria y aprendizaje altamente desarrollada.",
        "El sistema excretor elimina desechos y mantiene el equilibrio de fluidos en el cuerpo.",
        "Las células nerviosas transmiten señales eléctricas para coordinar las funciones corporales.",
        "El cuerpo humano tiene un sistema de soporte interno que incluye huesos y músculos.",
        "El sistema cardiovascular transporta sangre y nutrientes a través de una red de vasos sanguíneos.",
        "Las glándulas pituitarias en el cerebro regulan diversas funciones hormonales.",
        "El cuerpo humano puede ajustar su ritmo cardíaco y respiratorio en respuesta al ejercicio.",
        "El sistema inmunológico se adapta para reconocer y combatir nuevas infecciones.",
        "El cuerpo humano tiene una red compleja de vasos sanguíneos que transporta nutrientes y oxígeno.",
        "El sistema nervioso central y periférico trabaja en conjunto para controlar el cuerpo.",
        "El cuerpo humano tiene una capacidad para detectar y responder a estímulos externos.",
        "La piel tiene una función de barrera que protege el cuerpo contra daños y patógenos.",
        "El sistema esquelético proporciona un marco estructural para el cuerpo y protege órganos internos.",
        "El sistema nervioso autónomo regula funciones involuntarias como la digestión y la respiración.",
        "El cuerpo humano tiene una capacidad para adaptarse a cambios en el entorno y en la actividad física.",
        "El sistema linfático ayuda a drenar líquidos y a combatir infecciones.",
        "El cuerpo humano tiene una función de termorregulación que mantiene la temperatura interna.",
        "El sistema digestivo incluye órganos especializados para la descomposición y absorción de nutrientes.",
        "El cuerpo humano tiene un sistema de comunicación interno a través de neurotransmisores.",
        "La piel tiene la capacidad de sintetizar vitamina D a través de la exposición a la luz solar.",
        "El sistema musculoesquelético permite el movimiento y la estabilidad del cuerpo.",
        "El cuerpo humano puede responder a estímulos con reflejos rápidos e involuntarios.",
        "El sistema respiratorio incluye órganos especializados para el intercambio de gases.",
        "El sistema circulatorio incluye el corazón, vasos sanguíneos y sangre para el transporte de nutrientes.",
        "El sistema reproductivo permite la producción y el desarrollo de células reproductivas.",
        "El cuerpo humano tiene una capacidad para reconocer y reparar daños a nivel celular.",
        "El sistema endocrino regula el crecimiento, el metabolismo y la reproducción a través de hormonas.",
        "El cuerpo humano tiene una capacidad para adaptarse a cambios en la dieta y el ejercicio.",
        "El sistema nervioso periférico transmite señales entre el cerebro y el resto del cuerpo.",
        "La piel tiene una función importante en la regulación de la temperatura y la protección contra el sol.",
        "El sistema esquelético proporciona soporte estructural y permite el movimiento.",
        "El sistema digestivo descompone los alimentos y absorbe nutrientes para el cuerpo.",
        "El cuerpo humano tiene mecanismos para mantener el equilibrio interno y la homeostasis.",
        "El sushi se originó como una forma de conservar pescado.",
        "Las ostras pueden cambiar de sexo más de una vez.",
        "El tofu es conocido como 'queso de soja'.",
        "El queso parmesano se envejece al menos 12 meses.",
        "Las uvas se pueden secar al sol para hacer pasas.",
        "El aguacate es la fruta más calórica.",
        "El pepino es 95% agua.",
        "El wasabi real es raro fuera de Japón.",
        "El azúcar en frutas se llama fructosa.",
        "Las almendras son semillas, no frutos secos.",
        "El jamón serrano se cura al aire libre.",
        "La sal solía ser utilizada como moneda.",
        "El aceite de coco es sólido a temperatura ambiente.",
        "Las nueces son ricas en omega-3.",
        "El maíz dulce es una mutación genética.",
        "La piña es originaria de América del Sur.",
        "El cilantro puede tener sabor a jabón para algunas personas.",
        "El sushi significa 'arroz avinagrado'.",
        "El bacalao tiene poca grasa y es rico en proteínas.",
        "El perejil es un diurético natural.",
        "La nuez de Brasil es una de las fuentes más ricas de selenio.",
        "El café es la bebida más popular del mundo.",
        "El vinagre de manzana es conocido por sus propiedades digestivas.",
        "El té de jengibre puede aliviar el malestar estomacal.",
        "La sandía contiene licopeno, un antioxidante.",
        "Las bayas de goji son consideradas un superalimento.",
        "La calabaza contiene vitamina A.",
        "El brócoli es una fuente rica en calcio.",
        "El chocolate negro mejora la salud del corazón.",
        "El aceite de oliva es una grasa saludable.",
        "La chía es rica en fibra y antioxidantes.",
        "Las espinacas son una fuente de hierro y calcio.",
        "El plátano ayuda a reducir la presión arterial.",
        "La quinoa es una proteína completa.",
        "Las zanahorias son ricas en betacaroteno.",
        "El pimiento rojo tiene más vitamina C que una naranja.",
        "El ajo puede fortalecer el sistema inmunológico.",
        "El pescado graso es bueno para el cerebro.",
        "La cúrcuma es un antiinflamatorio natural.",
        "El salmón es una excelente fuente de omega-3.",
        "El arroz integral es más nutritivo que el blanco.",
        "El trigo sarraceno es libre de gluten.",
        "El aguacate es rico en grasas saludables.",
        "El kimchi es una fuente rica de probióticos.",
        "El miso es una pasta fermentada japonesa.",
        "Las semillas de girasol son ricas en vitamina E.",
        "El pistacho es uno de los frutos secos más antiguos.",
        "El café descafeinado no es 100% libre de cafeína.",
        "El queso roquefort es un queso azul francés.",
        "El ajo negro es ajo fermentado.",
        "Las ostras son afrodisíacas naturales.",
        "El vinagre balsámico se envejece durante años.",
        "El coco puede producir agua, leche y aceite.",
        "La miel es el único alimento que no se descompone.",
        "El yogur griego tiene más proteínas que el regular.",
        "El salmón silvestre es más nutritivo que el de criadero.",
        "Las uvas son uno de los cultivos más antiguos.",
        "El arroz inflado se inventó en 1904.",
        "Las trufas son uno de los alimentos más caros.",
        "El aguacate fue llamado 'fruto de los dioses' por los aztecas.",
        "El aceite de sésamo se usa en la medicina china.",
        "El jugo de remolacha mejora el rendimiento deportivo.",
        "El brócoli es una fuente rica en vitamina K.",
        "Las peras son ricas en antioxidantes.",
        "El limón ayuda a desintoxicar el cuerpo.",
        "El pan integral tiene más fibra que el pan blanco.",
        "El chile es originario de México.",
        "El ajo es un antibiótico natural.",
        "La calabaza es rica en antioxidantes.",
        "La avena es un superalimento para el corazón.",
        "El jengibre ayuda a la digestión.",
        "Las lentejas son una excelente fuente de proteína vegetal.",
        "El pescado tiene ácidos grasos esenciales.",
        "Las espinacas fortalecen los huesos.",
        "El aguacate regula el colesterol.",
        "El huevo es una de las proteínas más completas.",
        "El azúcar moreno contiene melaza.",
        "El higo es un fruto de gran antigüedad.",
        "El té matcha contiene antioxidantes.",
        "El pistacho es una fuente rica de vitamina B6.",
        "El maíz es el cereal más cultivado.",
        "El pan integral se digiere más lentamente.",
        "El ajo mejora la circulación.",
        "El aceite de coco se usa para cocinar y para la piel.",
        "El vinagre es un conservante natural.",
        "Las bayas son ricas en vitamina C.",
        "El hummus es una excelente fuente de proteína vegetal.",
        "El aguacate es excelente para la piel.",
        "El pimiento mejora la absorción del hierro.",
        "Las nueces contienen grasas saludables.",
        "El salmón protege el corazón.",
        "La manzana ayuda a limpiar los dientes.",
        "El yogur contiene bacterias beneficiosas.",
        "El chocolate amargo es bueno para el cerebro.",
        "El pepino es hidratante para el cuerpo.",
        "La quinoa es rica en fibra.",
        "El cacao crudo es uno de los alimentos más ricos en antioxidantes.",
        "El arroz negro es más nutritivo que el arroz blanco.",
        "Las semillas de lino son ricas en omega-3.",
        "El té verde acelera el metabolismo.",
        "El aguacate mejora la salud del corazón.",
        "La leche de almendras es baja en calorías.",
        "El jengibre reduce la inflamación.",
        "La col rizada es una fuente rica de vitamina A.",
        "El ajo protege el sistema inmunológico.",
        "Las moras son ricas en antioxidantes.",
        "El coco es alto en grasas saludables.",
        "El corazón humano late aproximadamente 100,000 veces al día.",
        "La piel es el órgano más grande del cuerpo humano.",
        "El cuerpo humano está compuesto en un 60% de agua.",
        "El cerebro humano tiene alrededor de 86 mil millones de neuronas.",
        "Las uñas crecen aproximadamente 3 mm al mes.",
        "Los huesos humanos son más fuertes que el acero del mismo peso.",
        "El ojo humano puede distinguir aproximadamente 10 millones de colores.",
        "La lengua humana tiene alrededor de 8,000 papilas gustativas.",
        "El hígado es el único órgano que puede regenerarse por completo.",
        "Los músculos más pequeños del cuerpo están en el oído medio.",
        "El cuerpo humano tiene 206 huesos en la adultez, pero 270 en la infancia.",
        "El esqueleto humano está compuesto por 206 huesos adultos, pero al nacer tiene 270.",
        "El estómago produce una nueva capa de mucus cada dos semanas para evitar que se digiera a sí mismo.",
        "El músculo más fuerte en relación con su tamaño es el masetero, el músculo que usamos para masticar.",
        "Cada célula en el cuerpo humano tiene un ciclo de vida diferente; algunas viven solo unos días, mientras que otras pueden durar toda la vida.",
        "Los huesos del oído medio (martillo, yunque y estribo) son los más pequeños del cuerpo.",
        "Los huesos son vivos y están en constante cambio; el proceso de remodelación ósea reemplaza el hueso viejo con hueso nuevo.",
        "El cuerpo humano produce aproximadamente 1 a 1.5 litros de saliva al día.",
        "El pulmón derecho es ligeramente más grande que el pulmón izquierdo.",
        "El cuerpo humano tiene aproximadamente 5 a 6 litros de sangre en promedio.",
        "Las células de la piel se renuevan cada 28 días.",
        "La piel tiene tres capas: epidermis, dermis y tejido subcutáneo.",
        "La sensación de cosquilleo es procesada en la parte del cerebro llamada corteza somatosensorial.",
        "El hígado filtra aproximadamente 1.4 litros de sangre por minuto.",
        "Los humanos tienen más de 600 músculos en el cuerpo.",
        "Las mujeres tienen más glándulas sudoríparas que los hombres.",
        "El cuerpo humano puede sobrevivir sin comida durante semanas, pero solo unos días sin agua.",
        "El oído humano puede detectar frecuencias desde 20 Hz hasta 20,000 Hz.",
        "Las huellas dactilares son únicas para cada individuo, incluso para los gemelos idénticos.",
        "El sistema nervioso central está compuesto por el cerebro y la médula espinal.",
        "El cuerpo humano puede generar su propio calor a través de la termogénesis.",
        "Las pestañas tienen una vida útil de aproximadamente 150 a 200 días.",
        "El cerebro representa aproximadamente el 2% del peso total del cuerpo pero utiliza el 20% de la energía del cuerpo.",
        "El músculo cardíaco es el único músculo que no se fatiga.",
        "Cada persona tiene una huella de lengua única.",
        "Los músculos del ojo son los más activos del cuerpo humano.",
        "El tejido adiposo (grasa) puede almacenar más energía que otros tipos de tejidos.",
        "La piel de los dedos tiene una capacidad única para detectar texturas finas.",
        "El intestino delgado tiene una longitud de aproximadamente 6 metros.",
        "El intestino grueso tiene una longitud de aproximadamente 1.5 metros.",
        "Los glóbulos rojos tienen una vida útil de aproximadamente 120 días.",
        "El hueso del fémur es el hueso más largo y fuerte del cuerpo.",
        "El ojo humano tiene tres tipos de conos que permiten distinguir colores: rojo, verde y azul.",
        "Las articulaciones de las manos son extremadamente flexibles y permiten una amplia gama de movimientos.",
        "El sistema inmunológico es responsable de proteger el cuerpo de infecciones y enfermedades.",
        "El páncreas produce insulina, que regula los niveles de azúcar en la sangre.",
        "Los músculos de los brazos y las piernas permiten una gran variedad de movimientos.",
        "El cuerpo humano tiene más de 2 millones de glándulas sudoríparas.",
        "Las células óseas llamadas osteoblastos son responsables de la formación de hueso nuevo.",
        "Los riñones filtran la sangre para eliminar desechos y producir orina.",
        "El hígado también está involucrado en la producción de proteínas importantes para la coagulación de la sangre.",
        "El cuerpo humano tiene un sistema de referencia propio para mantener el equilibrio.",
        "Las lágrimas tienen una función protectora y lubricante para los ojos.",
        "El cuerpo humano tiene un sistema de retroalimentación que regula la temperatura corporal.",
        "El sistema esquelético proporciona estructura y soporte al cuerpo.",
        "Las células de la piel son constantemente reemplazadas por nuevas células.",
        "El cerebro humano es aproximadamente un 75% de agua.",
        "El cuerpo humano tiene un mecanismo de curación natural para reparar heridas y lesiones.",
        "Los músculos del cuello permiten una amplia gama de movimientos de la cabeza.",
        "Las costillas protegen los órganos vitales en el pecho.",
        "El cuerpo humano puede regular la presión arterial para adaptarse a diferentes niveles de actividad.",
        "La piel tiene una función importante en la regulación de la temperatura corporal.",
        "El cuerpo humano tiene un sistema de glándulas que produce hormonas para regular funciones corporales.",
        "El sistema linfático ayuda a eliminar desechos y combatir infecciones.",
        "El sistema circulatorio transporta sangre, nutrientes y oxígeno a través del cuerpo.",
        "El cuerpo humano puede detectar cambios en la presión y la temperatura a través de receptores en la piel.",
        "El tejido conectivo incluye tendones, ligamentos y cartílago, que proporcionan soporte y flexibilidad.",
        "El sistema endocrino regula el crecimiento, el metabolismo y otras funciones a través de hormonas.",
        "Los músculos de la mandíbula son responsables de la masticación y la producción de sonidos.",
        "El cuerpo humano tiene una capacidad notable para adaptarse y aprender nuevas habilidades.",
        "El sistema respiratorio permite la entrada de oxígeno y la eliminación de dióxido de carbono.",
        "El cuerpo humano tiene mecanismos para mantener el equilibrio y la coordinación.",
        "Los receptores en la piel permiten la percepción del tacto, la presión y la temperatura.",
        "El cuerpo humano produce células sanguíneas en la médula ósea.",
        "Las articulaciones permiten el movimiento y la flexibilidad del cuerpo.",
        "El sistema digestivo descompone los alimentos para extraer nutrientes y energía.",
        "El cuerpo humano tiene un sistema de defensa natural contra patógenos y toxinas.",
        "El cerebro controla las funciones corporales y procesa la información sensorial.",
        "El cuerpo humano tiene una capacidad asombrosa para regenerarse y sanar.",
        "El sistema reproductivo permite la reproducción y el desarrollo de nuevas vidas.",
        "Las glándulas sebáceas producen aceite para mantener la piel y el cabello lubricados.",
        "El cuerpo humano tiene una capacidad de memoria y aprendizaje altamente desarrollada.",
        "El sistema excretor elimina desechos y mantiene el equilibrio de fluidos en el cuerpo.",
        "Las células nerviosas transmiten señales eléctricas para coordinar las funciones corporales.",
        "El cuerpo humano tiene un sistema de soporte interno que incluye huesos y músculos.",
        "El sistema cardiovascular transporta sangre y nutrientes a través de una red de vasos sanguíneos.",
        "Las glándulas pituitarias en el cerebro regulan diversas funciones hormonales.",
        "El cuerpo humano puede ajustar su ritmo cardíaco y respiratorio en respuesta al ejercicio.",
        "El sistema inmunológico se adapta para reconocer y combatir nuevas infecciones.",
        "El cuerpo humano tiene una red compleja de vasos sanguíneos que transporta nutrientes y oxígeno.",
        "El sistema nervioso central y periférico trabaja en conjunto para controlar el cuerpo.",
        "El cuerpo humano tiene una capacidad para detectar y responder a estímulos externos.",
        "La piel tiene una función de barrera que protege el cuerpo contra daños y patógenos.",
        "El sistema esquelético proporciona un marco estructural para el cuerpo y protege órganos internos.",
        "El sistema nervioso autónomo regula funciones involuntarias como la digestión y la respiración.",
        "El cuerpo humano tiene una capacidad para adaptarse a cambios en el entorno y en la actividad física.",
        "El sistema linfático ayuda a drenar líquidos y a combatir infecciones.",
        "El cuerpo humano tiene una función de termorregulación que mantiene la temperatura interna.",
        "El sistema digestivo incluye órganos especializados para la descomposición y absorción de nutrientes.",
        "El cuerpo humano tiene un sistema de comunicación interno a través de neurotransmisores.",
        "La piel tiene la capacidad de sintetizar vitamina D a través de la exposición a la luz solar.",
        "El sistema musculoesquelético permite el movimiento y la estabilidad del cuerpo.",
        "El cuerpo humano puede responder a estímulos con reflejos rápidos e involuntarios.",
        "El sistema respiratorio incluye órganos especializados para el intercambio de gases.",
        "El sistema circulatorio incluye el corazón, vasos sanguíneos y sangre para el transporte de nutrientes.",
        "El sistema reproductivo permite la producción y el desarrollo de células reproductivas.",
        "El cuerpo humano tiene una capacidad para reconocer y adaptarse a diferentes sabores y olores.",
        "El sistema excretor regula el equilibrio de líquidos y elimina desechos metabólicos.",
        "El cerebro humano es responsable de funciones cognitivas como el pensamiento y la memoria.",
        "El sistema endocrino regula el metabolismo y otras funciones corporales a través de hormonas.",
        "El cuerpo humano tiene una capacidad para mantener la homeostasis en diversas condiciones ambientales.",
        "La piel tiene una función en la percepción del tacto y la regulación de la temperatura.",
        "El sistema circulatorio y el sistema respiratorio trabajan juntos para suministrar oxígeno a los tejidos.",
        "El cuerpo humano tiene una red compleja de sistemas que cooperan para mantener la salud y el bienestar.",
        "El té verde mejora la concentración.",
        "El aceite de oliva es un antioxidante natural.",
        "El chocolate negro mejora el estado de ánimo.",
        "El mango es rico en vitamina C.",
        "El maíz es libre de gluten.",
        "El té de manzanilla alivia el estrés.",
        "El aguacate es una fuente rica de fibra.",
        "El queso feta es más ligero que otros quesos.",
        "El jugo de granada mejora la salud del corazón.",
        "Las zanahorias son buenas para la vista.",
        "El pepino reduce la inflamación.",
        "Las almendras mejoran la memoria.",
        "El arroz integral es bueno para el corazón.",
        "El limón equilibra los niveles de pH en el cuerpo.",
        "La calabaza es baja en calorías.",
        "El tofu es una excelente fuente de proteína vegetal.",
        "La sandía es buena para los riñones.",
        "El kiwi mejora la digestión.",
        "Las nueces son una excelente fuente de proteínas.",
        "La espinaca es una de las verduras más nutritivas.",
        "El aceite de oliva virgen extra es antiinflamatorio.",
        "La piña es una fuente de vitamina C.",
        "Las semillas de chía son ricas en fibra.",
        "La menta ayuda a la digestión.",
        "El aguacate contiene potasio.",
        "El tomate mejora la salud de la piel.",
        "La zanahoria es buena para los ojos.",
        "Las uvas ayudan a prevenir enfermedades cardíacas.",
        "El ajo reduce la presión arterial.",
        "El plátano es una fuente rica en potasio.",
        "La miel mejora el sistema inmunológico.",
        "El té verde reduce el colesterol.",
        "El brócoli tiene más vitamina C que una naranja.",
        "El jengibre alivia el dolor muscular.",
        "El pescado es una excelente fuente de proteínas.",
        "Las fresas son ricas en vitamina C.",
        "El arroz es uno de los alimentos más consumidos.",
        "El aceite de coco mejora la salud del cabello.",
        "El aguacate regula el colesterol.",
        "La luz del sol tarda aproximadamente 8 minutos en llegar a la Tierra.",
        "Los delfines tienen nombres únicos que usan para identificarse entre ellos.",
        "Los pulpos tienen tres corazones y su sangre es azul.",
        "Las abejas pueden reconocer rostros humanos.",
        "El cerebro humano tiene aproximadamente 86 mil millones de neuronas.",
        "El punto más alto de la Tierra es el monte Everest, con una altura de 8,848 metros sobre el nivel del mar.",
        "Las jirafas tienen la lengua de color negro o azul oscuro para protegerla de las quemaduras solares.",
        "Los elefantes son los únicos animales que no pueden saltar.",
        "Las medusas están formadas en un 95% por agua.",
        "El corazón de una ballena azul pesa tanto como un automóvil pequeño.",
        "Las huellas de los koalas son tan similares a las de los humanos que a veces los científicos las confunden en escenas del crimen.",
        "El récord de más tiempo sin dormir es de 11 días.",
        "El día más largo del año es el solsticio de verano.",
        "Los pingüinos pueden saltar hasta 2 metros fuera del agua.",
        "El colibrí es el único pájaro que puede volar hacia atrás.",
        "Las tortugas pueden respirar a través de su trasero.",
        "El río Amazonas es el más grande del mundo en términos de volumen de agua, pero no el más largo.",
        "Las estrellas de mar tienen la capacidad de regenerar brazos perdidos.",
        "El desierto del Sahara puede experimentar temperaturas tan bajas como -9°C en la noche.",
        "La miel nunca se echa a perder; se han encontrado frascos de miel en tumbas egipcias que aún son comestibles.",
        "Los camaleones pueden mover sus ojos de manera independiente.",
        "La Tierra es el único planeta conocido que tiene agua en estado líquido en su superficie.",
        "Las ranas pueden congelarse completamente durante el invierno y luego descongelarse en primavera.",
        "Las cebras son negras con rayas blancas, no al revés.",
        "Un grano de arena en la playa puede tener hasta 200 millones de años.",
        "Los humanos comparten aproximadamente el 60% de su ADN con las bananas.",
        "El récord de la mayor cantidad de calaveras de dinosaurios encontradas en un solo lugar es de 1,000.",
        "Las vacas tienen amigos y se estresan cuando están separados de ellos.",
        "Los tiburones existen desde hace más de 400 millones de años.",
        "Las hojas de los árboles se giran para evitar la exposición directa al sol en días calurosos.",
        "Las personas pueden reconocer hasta 5,000 olores diferentes.",
        "La velocidad de la luz en el vacío es de aproximadamente 299,792 kilómetros por segundo.",
        "El Mar Muerto es el punto más bajo en la superficie terrestre, a unos 430 metros por debajo del nivel del mar.",
        "Las ratas pueden sobrevivir sin agua durante más tiempo que los camellos.",
        "La Gran Muralla China no es una sola muralla continua, sino una serie de muros y fortificaciones.",
        "El animal más rápido en tierra es el guepardo, que puede alcanzar velocidades de hasta 100 km/h.",
        "La mayoría de los polvo que encuentras en tu hogar son células muertas de la piel.",
        "Las estrellas fugaces no son estrellas; son fragmentos de meteoritos que se queman al entrar en la atmósfera terrestre.",
        "El sistema solar tiene ocho planetas y cinco planetas enanos reconocidos.",
        "Las esmeraldas son más raras que los diamantes.",
        "El punto de ebullición del agua es de 100°C a nivel del mar, pero disminuye a medida que se asciende en altitud.",
        "Los flamencos son rosas debido a la dieta rica en betacarotenos de sus alimentos.",
        "Los erizos tienen hasta 5,000 púas en su cuerpo.",
        "Las serpientes tienen una lengua bifurcada para detectar olores.",
        "El cuerpo humano tiene 206 huesos en su adultez, pero al nacer tiene aproximadamente 270 huesos.",
        "Los calamares gigantes pueden tener tentáculos de hasta 12 metros de largo.",
        "Los anacondas son las serpientes más pesadas del mundo.",
        "Las medusas no tienen cerebro, corazón ni huesos.",
        "El Polo Norte está cubierto por una capa de hielo que flota sobre el océano Ártico.",
        "El sonido viaja más rápido en el agua que en el aire.",
        "Los dinosaurios vivieron en la Tierra hace aproximadamente 230 a 65 millones de años.",
        "El punto más profundo del océano es la Fosa de las Marianas, con una profundidad de más de 11,000 metros.",
        "Los caballos tienen un rango de visión de casi 360 grados.",
        "Los pandas gigantes comen aproximadamente 12 horas al día para mantenerse vivos.",
        "Los escorpiones brillan bajo la luz ultravioleta.",
        "Los tiburones tienen una capa de escamas en su piel que les ayuda a nadar más rápido y con menos resistencia.",
        "Las ranas pueden absorber oxígeno a través de su piel.",
        "Los cerdos son animales muy inteligentes y pueden aprender a hacer trucos similares a los perros.",
        "El Monte Everest crece a una tasa de aproximadamente 4 milímetros al año.",
        "Las arañas no son insectos; son arácnidos.",
        "El 70% de la superficie terrestre está cubierta por agua.",
        "Las ballenas jorobadas pueden cantar durante más de 20 minutos.",
        "Los hipopótamos pasan la mayor parte de su tiempo en el agua para mantenerse frescos.",
        "Los rayos caen en la Tierra aproximadamente 100 veces por segundo.",
        "Las vacas pueden reconocer a otras vacas y a los humanos por sus rostros.",
        "Los canguros no pueden caminar hacia atrás.",
        "La Tierra tiene un campo magnético que protege a los seres vivos de la radiación solar.",
        "La Luna está a una distancia promedio de la Tierra de aproximadamente 384,400 kilómetros.",
        "Los zorrillos tienen glándulas que producen un olor muy fuerte para defenderse de los depredadores.",
        "Las abejas pueden volar a una velocidad de hasta 24 kilómetros por hora.",
        "El corazón de un colibrí puede latir hasta 1,200 veces por minuto.",
        "Los pinguinos tienen un sistema de comunicación muy avanzado entre ellos.",
        "Las ballenas azules son los animales más grandes que jamás hayan existido en la Tierra.",
        "Los tigres tienen rayas únicas en su piel, similares a las huellas dactilares en los humanos.",
        "La médula ósea es el órgano responsable de producir células sanguíneas.",
        "Las hojas de los árboles cambian de color en otoño debido a la disminución de clorofila.",
        "Las tortugas pueden vivir más de 100 años.",
        "Los albatros tienen una envergadura de alas que puede llegar hasta 3.5 metros.",
        "Las arañas pueden tejer telas con patrones complejos y funcionales.",
        "Los lagartos pueden regenerar sus colas si las pierden.",
        "Los glaciares cubren aproximadamente el 10% de la superficie terrestre.",
        "Las nubes están formadas por pequeñas gotas de agua o cristales de hielo.",
        "Los camellos tienen tres párpados para proteger sus ojos de la arena.",
        "Las medusas pueden reproducirse asexualmente y sexualmente.",
        "Las avestruces son los pájaros más grandes y pesados del mundo.",
        "Los corales son animales marinos que forman grandes estructuras de arrecifes.",
        "Las anémonas de mar tienen células urticantes para atrapar presas.",
        "Los peces payaso viven en simbiosis con las anémonas de mar.",
        "El 90% de los datos en el mundo han sido creados en los últimos dos años.",
        "Las mariposas tienen sensores de sabor en sus patas.",
        "La gravedad de la Tierra es responsable de la forma esférica de los planetas.",
        "Los elefantes tienen una memoria excepcionalmente buena.",
        "Los lobos pueden recorrer hasta 30 kilómetros en un solo día en busca de comida.",
        "Los serpientes pueden sentir las vibraciones del suelo para detectar presas.",
        "Las mariposas monarca migran desde América del Norte hasta México cada año.",
        "Los delfines tienen una comunicación muy avanzada y compleja entre ellos.",
        "El esturión es uno de los peces más antiguos que aún existen en la Tierra.",
        "Las estrellas de mar pueden reproducirse a través de la regeneración de sus brazos.",
        "Los osos polares tienen piel negra debajo de su pelaje blanco.",
        "Las ballenas pueden comunicarse entre sí a través de sonidos a largas distancias.",
        "Los perezosos pasan la mayor parte del día durmiendo y moviéndose lentamente.",
        "Los flamingos pueden estar de pie sobre una pierna durante mucho tiempo.",
        "Las tortugas marinas pueden migrar a través de grandes distancias en el océano.",
        "El sistema inmunológico de los humanos puede identificar y atacar millones de diferentes patógenos.",
        "Las hormigas tienen una estructura social compleja y trabajan en equipo para sobrevivir.",
        "Los tiburones tienen un sentido del olfato muy agudo que les ayuda a encontrar presas.",
        "Los camaleones pueden cambiar de color para camuflarse con su entorno.",
        "Los osos panda pasan la mayor parte del tiempo comiendo bambú.",
        "Los cachalotes tienen el cerebro más grande de todos los animales.",
        "Las arañas pueden producir hilos de seda con diferentes propiedades según sus necesidades.",
        "Los pingüinos tienen un sistema de regulación térmica que les permite sobrevivir en climas fríos.",
        "Las abejas pueden volar hasta 5 kilómetros en busca de alimento.",
        "Las llamas tienen una capa de lana que las protege del frío.",
        "Los tigres tienen marcas de rayas únicas que pueden ser usadas para identificarlos.",
        "Las tortugas pueden detectar campos eléctricos para orientarse en el océano.",
        "Los calamares tienen ojos complejos que les permiten ver en la oscuridad del océano.",
        "Las ballenas jorobadas tienen una melodía única que cantan durante sus migraciones.",
        "Las ranas pueden cambiar el color de su piel para adaptarse a diferentes ambientes.",
        "Las cabras tienen pupilas rectangulares que les ayudan a tener una visión panorámica.",
        "Los camellos pueden beber hasta 40 litros de agua en una sola sesión.",
        "Las iguanas tienen un órgano especializado para detectar cambios en la temperatura.",
        "Los búhos tienen una audición extremadamente aguda que les ayuda a cazar en la oscuridad.",
        "Las medusas pueden ser bioluminiscentes y producir su propia luz.",
        "Las mantícoras son criaturas mitológicas con el cuerpo de un león y la cabeza de un humano.",
        "Los tiburones pueden detectar campos eléctricos generados por otros animales.",
        "Las mariposas pueden vivir en diferentes etapas de su vida en diferentes hábitats.",
        "Los corales tienen una relación simbiótica con algas unicelulares que les proporcionan nutrientes.",
        "Las serpientes pueden detectar cambios en la temperatura de su entorno con sus fosetas.",
        "Las estrellas fugaces son fragmentos de meteoritos que se desintegran al entrar en la atmósfera.",
        "Los búhos pueden girar su cabeza hasta 270 grados para ver en todas direcciones.",
        "Las arañas tienen ocho patas y pueden producir seda con diferentes propiedades.",
        "Las ranas tienen la capacidad de cambiar su color para camuflarse con su entorno.",
        "Los delfines pueden formar grupos llamados pods y cooperar para cazar.",
        "Las ballenas azules tienen un corazón del tamaño de un automóvil.",
        "Los pandas gigantes pasan la mayor parte de su tiempo comiendo bambú.",
        "Las tortugas pueden vivir tanto en el agua como en tierra, dependiendo de la especie.",
        "Los albatros pueden volar durante meses sin aterrizar.",
        "Las serpientes pueden detectar vibraciones en el suelo a través de sus mandíbulas.",
        "Las medusas pueden reproducirse asexualmente por gemación.",
        "Los pingüinos tienen un sistema de glándulas que les ayuda a eliminar el exceso de sal del agua.",
        "Las ranas tienen la capacidad de hibernar durante largos períodos de tiempo.",
        "Los tiburones tienen dientes afilados que se regeneran continuamente a lo largo de su vida.",
        "Las avestruces pueden correr a velocidades de hasta 70 kilómetros por hora.",
        "Las tortugas marinas pueden regresar a la playa donde nacieron para poner sus huevos.",
        "El ajo es un antibiótico natural.",
        "La avena mejora la salud digestiva.",
        "Las semillas de lino son ricas en fibra.",
        "El aceite de oliva es bueno para el corazón.",
        "El cacao crudo mejora la circulación.",
        "El brócoli es bueno para los huesos.",
        "El pepino es bajo en calorías.",
        "El mango mejora el sistema inmunológico.",
        "La quinoa es rica en proteínas.",
        "El aguacate mejora la absorción de nutrientes."
      ],
    };
  },
  getters: {
    getPigEasterEggs(): string[] {
      return this.pigEasterEggs;
    },
  },
});
// Esta app es realmente una PWA, ¡puedes usarla sin conexión! Además, se actualiza automáticamente en segundo plano.",
